### ISSUE TITLE
API Request

### ISSUE THREAD

**Issue by hydolMC** [LeviDevs/LunarClientSpoofer#1]
Make it so it works with https://github.com/kodak/LunarClientAPI

**Comment by leafypout** [comment]
I haven’t tested with this API specifically, I’ll look at it tomorrow. It should be an easy fix so most likely I’ll have a bypass ready for it tomorrow as well.

**Comment by hydolMC** [comment]
ok thank you

**Comment by hydolMC** [comment]
have u had a look yet

**Comment by leafypout** [comment]
Hi, sorry for the late response. I have tried the latest version of the plugin you linked with the latest version of the mod (1.1-PRODUCTION) and it works fine for me. Be sure that you're using the latest version of the mod (1.1) as the old version does not bypass some API's.
